name: Deploy React App

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.6.1 # Adjust to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          npm install -g gh-pages
          gh-pages -d build

